apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: linear-regr-infer-0 # Executable ID (max length 64 lowercase-hypen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `text-clf-infer-tutorial-1234`
  annotations:
    scenarios.ai.sap.com/description: "Train and serve a linear regression model."
    scenarios.ai.sap.com/name: linear-regr-scenario
    executables.ai.sap.com/description: "Serve the model and make it available for inference requests."
    executables.ai.sap.com/name: "linear-regr-infer-exec"
  labels:
    scenarios.ai.sap.com/id: linear-regr # Unique ID for the AI scenario.
    ai.sap.com/version: "0.0.1"
spec:
  inputs:
    parameters: []
    artifacts:
    # Name for the trained model. Must not include hyphens (-), otherwise error is thrown.
    # Make sure the same name is used in line 43.
      - name: regrmodel
  template:
    apiVersion: "serving.kubeflow.org/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kfserving-container
          image: "docker.io/<docker-hub-username>/linear-regr:0.0.2"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.regrmodel}}"